CREATE SCHEMA DEMO;

CREATE TABLE PROBLEMA(
ID INT,
NOME CHAR(100),
CLASSE CHAR(100)
);

CREATE TABLE SOLUCAO(
ID INT,
NOME CHAR(100),
CLASSE CHAR(100)
);

INSERT INTO PROBLEMA (ID, NOME)
VALUES (1, 'Não liga'), 
(2, 'Travando');

INSERT INTO SOLUCAO(ID, NOME)
VALUES (1, 'Removido mal contato'),
(2, 'HD substituído');