CREATE SCHEMA DEMO;
SET SCHEMA DEMO;

CREATE TABLE PROBLEMA(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME CHAR(100),
CLASSE CHAR(100),
PRIMARY KEY (ID)
);

CREATE TABLE SOLUCAO(
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOME CHAR(100),
CLASSE CHAR(100)
);

INSERT INTO PROBLEMA (NOME)
VALUES ('Não liga'), 
('Travando');

INSERT INTO SOLUCAO(ID, NOME)
VALUES (1, 'Removido mal contato'),
(2, 'HD substituído');